---
name: CI
on: [push, pull_request]

jobs:
  make_test:
    name: Original Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          # - macos-13
          # - macos-12
          # - macos-11
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: dependencies
        run: |
          if which brew > /dev/null; then
            brew install gawk
            which gawk
          fi
          if which apt > /dev/null; then
            sudo apt update
            sudo apt install -y make sqlite3
          fi
      - name: oldtest
        run: |
          make test
# vim: set ft=yaml:ts=2:sw=2:expandtab :
